### ISSUE TITLE
Permission denied for ```n latest```

### ISSUE THREAD

**Issue by oiojin831** [trevordmiller/shell-scripts#23]
I didn't run the script since I wanted to try it one by one to know what's going on.

https://github.com/tj/n/issues/416 in the thread it says that brew is no longer changing the ownership.

Is this only happening if I try to run the script one by one or even running the whole script?

Thanks for the great script 😄

**Comment by trevordmiller** [comment]
@oiojin831 Thanks for the comment. This is my own personal script that works for me but feel free to post issues or read the katesr documentation on the n library :)
